spring.application.name=fitness-app
data.courses.path=src/main/resources/data/courses.json
data.signups.path=src/main/resources/data/signups.json
data.waitlist.path=src/main/resources/data/waitlistEntries.json
data.members.path=src/main/resources/data/members.json
data.subscriptions.path=src/main/resources/data/subscriptions.json
data.payments.path=src/main/resources/data/payments.json
data.receipts.path=src/main/resources/data/receipts.json
data.checkins.path=src/main/resources/data/checkins.json
data.locations.path=src/main/resources/data/locations.json
data.users.path=src/main/resources/data/users.json