spring.application.name=fitness-app
data.courses.path=src/main/resources/data/courses.json
data.locations.path=src/main/resources/data/locations.json
data.signups.path=src/main/resources/data/signups.json
data.waitlist.path=src/main/resources/data/waitlistEntries.json
